const SHOP_DATA = [
  {
    title: "Hats",
    items: [
      {
        id: 1,
        name: "Brown Brim",
        img: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        price: 25,
        timeStamp: new Date(),
      },
      {
        id: 2,
        name: "Blue Beanie",
        img: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 18,
        timeStamp: new Date(),
      },
      {
        id: 3,
        name: "Brown Cowboy",
        img: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        price: 35,
        timeStamp: new Date(),
      },
      {
        id: 4,
        name: "Grey Brim",
        img: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        price: 25,
        timeStamp: new Date(),
      },
      {
        id: 5,
        name: "Green Beanie",
        img: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        price: 18,
        timeStamp: new Date(),
      },
      {
        id: 6,
        name: "Palm Tree Cap",
        img: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        price: 14,
        timeStamp: new Date(),
      },
      {
        id: 7,
        name: "Red Beanie",
        img: "https://i.ibb.co/bLB646Z/red-beanie.png",
        price: 18,
        timeStamp: new Date(),
      },
      {
        id: 8,
        name: "Wolf Cap",
        img: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 14,
        timeStamp: new Date(),
      },
      {
        id: 9,
        name: "Blue Snapback",
        img: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        price: 16,
        timeStamp: new Date(),
      },
    ],
  },
  {
    title: "Sneakers",
    items: [
      {
        id: 10,
        name: "Adidas NMD",
        img: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        price: 220,
        timeStamp: new Date(),
      },
      {
        id: 11,
        name: "Adidas Yeezy",
        img: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
        timeStamp: new Date(),
      },
      {
        id: 12,
        name: "Black Converse",
        img: "https://i.ibb.co/bPmVXyP/black-converse.png",
        price: 110,
        timeStamp: new Date(),
      },
      {
        id: 13,
        name: "Nike White AirForce",
        img: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 160,
        timeStamp: new Date(),
      },
      {
        id: 14,
        name: "Nike Red High Tops",
        img: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 160,
        timeStamp: new Date(),
      },
      {
        id: 15,
        name: "Nike Brown High Tops",
        img: "https://i.ibb.co/fMTV342/nike-brown.png",
        price: 160,
        timeStamp: new Date(),
      },
      {
        id: 16,
        name: "Air Jordan Limited",
        img: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
        timeStamp: new Date(),
      },
      {
        id: 17,
        name: "Timberlands",
        img: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
        timeStamp: new Date(),
      },
    ],
  },
  {
    title: "Jackets",
    items: [
      {
        id: 18,
        name: "Black Jean Shearling",
        img: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        price: 125,
        timeStamp: new Date(),
      },
      {
        id: 19,
        name: "Blue Jean Jacket",
        img: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        price: 90,
        timeStamp: new Date(),
      },
      {
        id: 20,
        name: "Grey Jean Jacket",
        img: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        price: 90,
        timeStamp: new Date(),
      },
      {
        id: 21,
        name: "Brown Shearling",
        img: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        price: 165,
        timeStamp: new Date(),
      },
      {
        id: 22,
        name: "Tan Trench",
        img: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        price: 185,
        timeStamp: new Date(),
      },
    ],
  },
  {
    title: "Womens",
    items: [
      {
        id: 23,
        name: "Blue Tanktop",
        img: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        price: 25,
        timeStamp: new Date(),
      },
      {
        id: 24,
        name: "Floral Blouse",
        img: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        price: 20,
        timeStamp: new Date(),
      },
      {
        id: 25,
        name: "Floral Dress",
        img: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        price: 80,
        timeStamp: new Date(),
      },
      {
        id: 26,
        name: "Red Dots Dress",
        img: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        price: 80,
        timeStamp: new Date(),
      },
      {
        id: 27,
        name: "Striped Sweater",
        img: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        price: 45,
        timeStamp: new Date(),
      },
      {
        id: 28,
        name: "Yellow Track Suit",
        img: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        price: 135,
        timeStamp: new Date(),
      },
      {
        id: 29,
        name: "White Blouse",
        img: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 20,
        timeStamp: new Date(),
      },
    ],
  },
  {
    title: "Mens",
    items: [
      {
        id: 30,
        name: "Camo Down Vest",
        img: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 325,
        timeStamp: new Date(),
      },
      {
        id: 31,
        name: "Floral T-shirt",
        img: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 20,
        timeStamp: new Date(),
      },
      {
        id: 32,
        name: "Black & White Longsleeve",
        img: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 25,
        timeStamp: new Date(),
      },
      {
        id: 33,
        name: "Pink T-shirt",
        img: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 25,
        timeStamp: new Date(),
      },
      {
        id: 34,
        name: "Jean Long Sleeve",
        img: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 40,
        timeStamp: new Date(),
      },
      {
        id: 35,
        name: "Burgundy T-shirt",
        img: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 25,
        timeStamp: new Date(),
      },
    ],
  },
];

export default SHOP_DATA;
